export const TOGGLE_LOGIN = "[LOGIN] TOGGLE_LOGIN";
export const SHOW_LOGIN_TAB = "[LOGIN] SHOW_LOGIN_TAB";
export const SHOW_REGISTER_TAB = "[LOGIN] SHOW_REGISTER_TAB";
export const REQUEST_LOGIN = "[LOGIN] REQUEST_LOGIN";
export const REQUEST_REGISTER = "[REGISTER] REQUEST_REGISTER";

export const UPDATE_LOGIN = "[LOGIN] UPDATE_LOGIN";
export const UPDATE_REGISTER = "[REGISTER] UPDATE_REGISTER";