export const LOADING_PRODUCTS = "[PRODUCT] LOADING_PRODUCTS";
export const LOADING_PRODUCTS_FULFILLED = "[PRODUCT] LOADING_PRODUCTS_FULFILLED";
export const LOADING_PRODUCTS_FAILED = "[PRODUCT] LOADING_PRODUCTS_FAILED";

export const TOGGLE_PRODUCT_DETAIL = "[PRODUCT] TOGGLE_PRODUCT_DETAIL";